"""Persistent discovery and candidacy layer scaffolding."""

from denbust.discovery.base import (
    DiscoveryContext,
    DiscoveryEngine,
    SourceCandidateProducer,
    SourceDiscoveryContext,
)
from denbust.discovery.models import (
    CandidateProvenance,
    CandidateStatus,
    ContentBasis,
    DiscoveredCandidate,
    DiscoveryQuery,
    DiscoveryQueryKind,
    DiscoveryRun,
    DiscoveryRunStatus,
    FetchStatus,
    PersistentCandidate,
    ProducerKind,
    ScrapeAttempt,
    ScrapeAttemptKind,
)
from denbust.discovery.persistence import (
    CandidateStore,
    DiscoveryRunStore,
    ProvenanceStore,
    ScrapeAttemptStore,
)
from denbust.discovery.source_native import (
    PersistedSourceDiscovery,
    SourceDiscoveryAdapter,
    build_candidate_id,
    merge_discovered_candidate,
    persist_discovered_candidates,
    raw_article_to_discovered_candidate,
)
from denbust.discovery.state_paths import (
    DiscoveryStatePaths,
    discovery_snapshot_filename,
    resolve_discovery_state_paths,
    write_candidate_jsonl,
    write_discovery_run_snapshot,
    write_metrics_snapshot,
)
from denbust.discovery.storage import (
    CompositeDiscoveryPersistence,
    DiscoveryPersistence,
    NullDiscoveryPersistence,
    StateRepoDiscoveryPersistence,
    SupabaseDiscoveryPersistence,
    create_discovery_persistence,
)

__all__ = [
    "CandidateProvenance",
    "CandidateStatus",
    "CandidateStore",
    "CompositeDiscoveryPersistence",
    "ContentBasis",
    "DiscoveredCandidate",
    "DiscoveryContext",
    "DiscoveryEngine",
    "DiscoveryPersistence",
    "DiscoveryQuery",
    "DiscoveryQueryKind",
    "DiscoveryRun",
    "DiscoveryRunStatus",
    "DiscoveryRunStore",
    "DiscoveryStatePaths",
    "FetchStatus",
    "NullDiscoveryPersistence",
    "PersistedSourceDiscovery",
    "PersistentCandidate",
    "ProducerKind",
    "ProvenanceStore",
    "SourceDiscoveryAdapter",
    "StateRepoDiscoveryPersistence",
    "ScrapeAttempt",
    "ScrapeAttemptKind",
    "ScrapeAttemptStore",
    "SourceCandidateProducer",
    "SourceDiscoveryContext",
    "SupabaseDiscoveryPersistence",
    "build_candidate_id",
    "create_discovery_persistence",
    "discovery_snapshot_filename",
    "merge_discovered_candidate",
    "persist_discovered_candidates",
    "resolve_discovery_state_paths",
    "raw_article_to_discovered_candidate",
    "write_candidate_jsonl",
    "write_discovery_run_snapshot",
    "write_metrics_snapshot",
]
